Repository VB10/HealthoUI, pull requests merged in 2019-08, with the labels that each got.

#1 Add a Codacy badge to README.md
  README.md
Labels: help wanted

#2 Settings & Tabbar & Profile
  assets/icons/menu.png
  lib/main.dart
  lib/ui/shared/constants.dart
  lib/ui/shared/text_style.dart
  lib/ui/shared/ui_helper.dart
  lib/ui/shared/widget/settings_card_widget.dart
  lib/ui/views/home/home_tab_view.dart
  lib/ui/views/home/settings/profile_view.dart
  lib/ui/views/home/settings_view.dart
  pubspec.yaml
Labels: duplicate, enhancement, good first issue

#3 notification and reminder page add
  lib/ui/shared/constants.dart
  lib/ui/shared/text_style.dart
  lib/ui/shared/ui_helper.dart
  lib/ui/views/home/home_tab_view.dart
  lib/ui/views/home/notifcation/notification_view.dart
  lib/ui/views/home/reminder/reminder_view.dart
  lib/ui/views/home/settings_view.dart
Labels: enhancement, good first issue, help wanted

#4 tabbar fix
  lib/ui/shared/constants.dart
  lib/ui/views/home/home_tab_view.dart
Labels: bug, enhancement

#5 last fix
  lib/ui/views/home/home_tab_view.dart
  lib/ui/views/home/notifcation/notification_view.dart
  lib/ui/views/home/settings_view.dart
Labels: bug

#6 brightness color get android & ios
  lib/ui/views/home/home_tab_view.dart
Labels: enhancement

#7 Dev
  README.md
  assets/langs/en-US.json
  assets/langs/tr-TR.json
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/core/form_helper.dart
  lib/main.dart
  lib/ui/shared/constants.dart
  lib/ui/views/login/phone_view.dart
  pubspec.lock
  pubspec.yaml
  test/ui/login.dart
  test/unit/login.dart
  test/widget_test.dart
Labels: enhancement, good first issue
